server:
  port: 10086
spring:
  application:
    name: ly-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8083/eureka
    #register-with-eureka: false
    #fetch-registry: false
    #registry-fetch-interval-seconds: 5
    #prefer-ip-address: true
    #ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api
  routes: #添加路由前缀
    ly-cloudconsumer: /cloudtest/**
  #retryable: true
ribbon:
  ConnectTimeout: 1000 #连接超时时间(ms)
  ReadTimeout: 3000 #通信超时时间(ms)
  #OkToRetryOnAllOperations: true #是否对所有操作重试
  #MaxAutoRetriesNextServer: 1 #同一服务不同实例的重试次数
  MaxAutoRetries: 0 #同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 50000 #熔断超时时长默认：10000ms，不设置长点容易报超时异常