server:
  port: 8081
  servlet:
    context-path: /cloud_test

spring:
  application:
    name: ly-cloudconsumer
    #访问页面所需的配置
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    ds0:
      url: jdbc:mysql://localhost:3306/yun?serverTimezone=UTC
      username: root
      password: 1234
      hikari:
        maximum-pool-size: 30
        minimum-idle: 10
      type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
  redis:
    #database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1
    port: 6379
    password: # Redis服务器连接密码（默认为空）
    #pool:
      #max-active: 100 #连接池最大连接数（使用负值表示没有限制）
      #max-idle: 10 # 连接池中的最大空闲连接
      #max-wait: 100000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      #timeout: 500 # 连接超时时间（毫秒）

  #源码说明：eureka生效的条件
  #@ConditionalOnProperty(
  #value = {"eureka.client.enabled"},
  #matchIfMissing = true
  #)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8083/eureka

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml #指定mappper.xml的路径

#设置日志级别
logging:
  level:
    com.cloud.consumer: debug

#打开feign对hustrix的支持否则FollBACK方法不生效
feign:
  hystrix:
    enabled: true


